Support multiple frameworks
csqrl/roactify-plugin pull request #3
Opened 2022-02-11 01:04 UTC by boatbomber

This is a pretty hefty update. Instead of being tied specifically to Roact, this PR introduces framework agnosticism and adds support for Fusion and Regular.

To go along with that, I've renamed it to Codify. It's a bit of a double meaning pun, since it turns UI into code (code-ify) but also the word "codify" means to make systematic and structured. Fitting! Not sure what to do about the repository name though.

I updated the spritesheet to include icons for the frameworks, which adds a lot to the polished feel of the dropdown.

I also fixed a couple bugs with TextInput sizing and highlighting.

![image](https://user-images.githubusercontent.com/40185666/153528644-a3bb1ee6-384a-4697-8de8-a531d75dcae3.png)

2022-02-11 03:43 UTC, chriscerie requested changes

2022-02-11 10:49 UTC, csqrl commented
**[`b8a0684` (#3)](https://github.com/csqrl/roactify-plugin/pull/3/commits/b8a0684c705539c5eea84ac08a2811665e2511eb) - Support icon colours in dropdown**
* This change allows dropdowns to support icon colours, which means Fusion can have both its light and dark icons
* Padding reduced around the border of the dropdown popover

![RobloxStudioBeta_m6RfDk3msF](https://user-images.githubusercontent.com/21029087/153578053-74cc4c21-f052-48cd-ad61-9b3fb4f15123.gif)

**[`c4f11f2` (#3)](https://github.com/csqrl/roactify-plugin/pull/3/commits/c4f11f2fa0af7589501bb79e35a255200789396e) - Fix border overlapping+cleanup**
The changes made to TextInputs which calculated the size (rather than relying on AutomaticSize) caused the bottom border to be overlapped by the contents (which was more noticeable in light mode)

![image](https://user-images.githubusercontent.com/21029087/153578396-ce7cc668-e1a7-43d9-86fd-4a6ab72b5d1b.png)

![image](https://user-images.githubusercontent.com/21029087/153578710-e069ec2e-5f29-44ba-9523-a3b473a64b82.png)

2022-02-11 18:26 UTC, chriscerie requested changes
In React it's idiomatic to use the logical `and` operator in place of ternary if you're switching between an element and nil.

2022-02-11 18:26 UTC, chriscerie commented on src/Components/Dropdown/Button.lua
> +					else nil,
```suggestion
				icon = props.icon and e(Icon, {
					icon = props.icon,
					order = if props.iconPosition == "end" then 40 else 10,
					colour = if props.iconColour then props.iconColour else colours.foreground,
					size = 16,
				}),
```

2022-02-11 18:26 UTC, chriscerie commented on src/Components/Dropdown/OptionButton.lua
> +			else nil,
```suggestion
		icon = props.icon and e(Icon, {
			icon = props.icon,
			order = if props.iconPosition == "end" then 40 else 10,
			colour = if props.iconColour then props.iconColour else colours.foreground,
			size = 16,
		}),
```

2022-02-11 18:55 UTC, csqrl commented on src/Components/Dropdown/Button.lua
> +					else nil,
You're absolutely right, and this much looks cleaner! I believe I had issues with that in the past, hence why I used ternaries, but I don't seem to be having any issues with this now 🤷

2022-02-11 21:15 UTC, chriscerie commented on src/Components/Checkbox/init.lua
> +	end, { props.disabled, props.value, hover, press })
```suggestion
	end, { props.disabled, hover, press })
```

2022-02-11 21:36 UTC, csqrl commented on src/Components/Checkbox/init.lua
> +	end, { props.disabled, props.value, hover, press })
Good catch!

2022-02-11 22:23 UTC, csqrl commented on src/Components/Pages/Home.lua
> +					end, {}),
Thanks! I've addressed this in [`636771e` (#3)](https://github.com/csqrl/roactify-plugin/pull/3/commits/636771e5164d2afe81d57c07b8d90a95a11e055e). The dropdown props are being memoised at the root of the component(s), rather than within its return value

2022-02-12 20:26 UTC, mkargus commented
Heads up: Seems like the Wally.toml didn't get the name change.

2022-02-12 20:30 UTC, csqrl commented
> Heads up: Seems like the Wally.toml didn't get the name change.

already covered in one of my local commits. actually the description was wrong for it too, since I just copied the `wally.toml` from one of my plugins 😅

2022-02-15 21:48 UTC, merged